org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=26.2
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[26.2,27)
# The NeoForge version must agree with the Minecraft version to get a valid artifact
neo_version=26.2.0.67

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
mod_id=colorapocalypse
# The human-readable display name for the mod.
mod_name=ColorApocalypse
# The license of the mod. Review your options at https://choosealicense.com/.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.0.0
# The group ID for the mod.
mod_group_id=org.furranystudio
# The authors of the mod.
mod_authors=Maxime66410
# The description of the mod.
mod_description=ColorApocalypse is a multiplayer Minecraft mod (NeoForge-compatible) that turns your survival experience into a chaotic and unpredictable challenge. The concept is simple: the world gradually loses its colors, and each color that disappears causes the instant destruction of all associated blocks in your world.
